### PR TITLE
Add angular star count

### PR DESCRIPTION
**Pull request by lifez**
- Added Angular

### CODE REVIEW

**Comment by vovk1805** [comment]
Make sense replacing axios by native fetch?

**Comment by lifez** [comment]
I think axios is better

**Comment by vovk1805** [comment]
yep, but for just fetching simple json, why need another dependency

**Comment by stursby** [comment]
I appreciate the work, but this really dumb little site is just for Vue and React... it's even in the URL ha. Going to close for now, sorry.

**Comment by lifez** [comment]
Just a joke haha

**Pull request closed without merging**
